var map = {
	switch: { id: 'switch', type: 'switch', next: ['s01', 's21', 's31'], firewall: [] },
	t0: { id: 't0', type: 'home', next: ['c01', 's03'], firewall: [] },
	s01: { id: 's01', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['switch', 's02'], firewall: [] },
	s02: { id: 's02', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['s01', 's03'], firewall: [] },
	s03: { id: 's03', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['s02', 't0'], firewall: [] },
	c01: { id: 'c01', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['c02'], firewall: [] },
	c02: { id: 'c02', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['c03'], firewall: [] },
	c03: { id: 'c03', type: 'dhcp', next: ['c04'], firewall: [] },
	c04: { id: 'c04', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['c05'], firewall: [] },
	c05: { id: 'c05', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['t1'], firewall: [] },
	t1: { id: 't1', type: 'home', next: ['c11'], firewall: [] },
	c11: { id: 'c11', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['c12'], firewall: [] },
	c12: { id: 'c12', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['c13'], firewall: [] },
	c13: { id: 'c13', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['c14'], firewall: [] },
	c14: { id: 'c14', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['c15'], firewall: [] },
	c15: { id: 'c15', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['t2'], firewall: [] },
	t2: { id: 't2', type: 'home', next: ['c21', 's23'], firewall: [] },
	s21: { id: 's21', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['switch', 's22'], firewall: [] },
	s22: { id: 's22', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['s21', 's23'], firewall: [] },
	s23: { id: 's23', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['s22', 't2'], firewall: [] },
	c21: { id: 'c21', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['c22'], firewall: [] },
	c22: { id: 'c22', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['c23'], firewall: [] },
	c23: { id: 'c23', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['c24'], firewall: [] },
	c24: { id: 'c24', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['c25'], firewall: [] },
	c25: { id: 'c25', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['t3'], firewall: [] },
	t3: { id: 't3', type: 'home', next: ['c31', 's33'], firewall: [] },
	s31: { id: 's31', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['switch', 's32'], firewall: [] },
	s32: { id: 's32', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['s31', 's33'], firewall: [] },
	s33: { id: 's33', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['s32', 't3'], firewall: [] },
	c31: { id: 'c31', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['c32'], firewall: [] },
	c32: { id: 'c32', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['c33'], firewall: [] },
	c33: { id: 'c33', type: 'dhcp', next: ['c34'], firewall: [] },
	c34: { id: 'c34', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['c35'], firewall: [] },
	c35: { id: 'c35', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['t4'], firewall: [] },
	t4: { id: 't4', type: 'home', next: ['c41'], firewall: [] },
	c41: { id: 'c41', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['c42'], firewall: [] },
	c42: { id: 'c42', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['c43'], firewall: [] },
	c43: { id: 'c43', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['c44'], firewall: [] },
	c44: { id: 'c44', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['c45'], firewall: [] },
	c45: { id: 'c45', type: 'server', owner: null, level: 0, price: 500, tolls: 0, next: ['t0'] }
}
module.exports = map;
